### ISSUE TITLE
The tokenizer failed to tokenize a smiles

### ISSUE THREAD

**Issue by zhaisilong** [jinhojsk515/spmm#2]
# SPMM_models.py
print(text_input.input_ids[:4], prop[:4], text_input.input_ids.shape)
exit()

>>> tensor([[2, 2, 1, 3],
        [2, 2, 1, 3],
        [2, 2, 1, 3],
        [2, 2, 1, 3]], device='cuda:0') tensor([[ 2.3104, -1.5346, -1.2431, -1.0015, -1.1336, -1.4145, -1.1286, -1.2634,
         -0.8863, -0.7488, -1.5606, -0.3628, -1.3415, -0.0982, -1.4446,  0.8066,
          0.3274, -0.2114,  1.6937,  1.5113, -1.3633, -1.5179, -0.8140, -0.4515,
          1.9547, -1.3326, -1.9357, -1.9357, -0.3264,  0.5493,  0.1936, -1.1924,
         -1.4456, -1.1348, -1.2925, -0.4183, -0.7510, -0.8534, -1.1132, -0.8680,
         -1.4712, -0.9739, -1.1667, -1.5777, -0.0343,  0.1643, -0.3701, -0.6282,
         -0.7153, -1.2057, -1.8758, -1.4532, -1.2087],
        [ 0.3362, -0.9400, -0.9879, -0.9637, -1.0960, -0.9825, -1.0188, -1.1606,...........

**Comment by zhaisilong** [comment]
>>> from transformers import BertTokenizer, WordpieceTokenizer
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
>>> tokenizer = BertTokenizer(vocab_file="vocab_bpe_300.txt", do_lower_case=False, do_basic_tokenize=False)
>>> tokenizer.wordpiece_tokenizer = WordpieceTokenizer(vocab=tokenizer.vocab, unk_token=tokenizer.unk_token, max_input_chars_per_word=250)
>>> tokenizer("CC(NC(=O)C(=O)NCCCCC#N)c1cccc(C(F)(F)F)c1")
{'input_ids': [2, 1, 3], 'token_type_ids': [0, 0, 0], 'attention_mask': [1, 1, 1]}

**Comment by sunyrain** [comment]
Have you solved the issue? Same question

**Comment by chenlong164** [comment]
I'm having the same issue，it seems can't encoder all SMILES we provide,only a few of SMILES can be exactly encoder

**Comment by jinhojsk515** [comment]
There are several reasons that can cause this:

1. When you put SMILES with a length more than "max_input_chars_per_word"(which is currently 250), the entire input is tokenized into [UNK]. You can simply change this value if you want to use longer SMILES.
2. Did you use the exact environment setting described in requirements.txt? We found that the tokenization process works fine with the version of the library tokenizers==0.13.3, but malfunctions as you reported from the version tokenizers==0.14.1.
3. In the current implementation with the current environment, the input should start with '[CLS]'{e.g. tokenizer('[CLS]CC(C)=CCCC(C)=CC=O')}, and the first token should be discarded (to remove the attached [CLS]). Although these procedures are all handled in the dataset.py/training/fine-tuning/inference scripts, we are sorry for the clumsiness in the direct usage of the tokenizer. We're trying to modify the implementation to make it more straightforward.

I hope one of the above will solve your issues.

**Comment by sunyrain** [comment]
> There are several reasons that can cause this:有几个原因可能导致这种情况：
> 
> 1. When you put SMILES with a length more than "max_input_chars_per_word"(which is currently 250), the entire input is tokenized into [UNK]. You can simply change this value if you want to use longer SMILES.当您放置长度超过“max_input_chars_per_word”（当前为 250）的 SMILES 时，整个输入将被标记为 [UNK]。如果您想使用更长的 SMILES，只需更改此值即可。
> 2. Did you use the exact environment setting described in requirements.txt? We found that the tokenization process works fine with the version of the library tokenizers==0.13.3, but malfunctions as you reported from the version tokenizers==0.14.1.您是否使用了requirements.txt中描述的确切环境设置？我们发现标记化过程在库 tokenizers==0.13.3 的版本中工作正常，但如您从版本 tokenizers==0.14.1 报告的那样出现故障。
> 3. In the current implementation with the current environment, the input should start with '[CLS]'{e.g. tokenizer('[CLS]CC(C)=CCCC(C)=CC=O')}, and the first token should be discarded (to remove the attached [CLS]). Although these procedures are all handled in the dataset.py/training/fine-tuning/inference scripts, we are sorry for the clumsiness in the direct usage of the tokenizer. We're trying to modify the implementation to make it more straightforward.在当前环境的当前实现中，输入应以“[CLS]”开头{例如tokenizer('[CLS]CC(C)=CCCC(C)=CC=O')}，并且第一个令牌应该被丢弃（以删除附加的 [CLS]）。尽管这些过程都是在 dataset.py/training/fine-tuning/inference 脚本中处理的，但我们对直接使用分词器的笨拙表示歉意。我们正在尝试修改实现以使其更加简单。
> 
> I hope one of the above will solve your issues.我希望上述之一能够解决您的问题。

Thank you very much ,the third method solved my problem.

**Comment by chenlong164** [comment]
> There are several reasons that can cause this:
> 
> 1. When you put SMILES with a length more than "max_input_chars_per_word"(which is currently 250), the entire input is tokenized into [UNK]. You can simply change this value if you want to use longer SMILES.
> 2. Did you use the exact environment setting described in requirements.txt? We found that the tokenization process works fine with the version of the library tokenizers==0.13.3, but malfunctions as you reported from the version tokenizers==0.14.1.
> 3. In the current implementation with the current environment, the input should start with '[CLS]'{e.g. tokenizer('[CLS]CC(C)=CCCC(C)=CC=O')}, and the first token should be discarded (to remove the attached [CLS]). Although these procedures are all handled in the dataset.py/training/fine-tuning/inference scripts, we are sorry for the clumsiness in the direct usage of the tokenizer. We're trying to modify the implementation to make it more straightforward.
> 
> I hope one of the above will solve your issues.

thanks for your patient reply，but i still have same question,for example i can encoder the SMILES '[CLS]CC(C)=CCCC(C)=CC=O' and it result is tensor([[  2,   2, 134, 207, 248, 207, 151,  37,   3]])，but when i encoder other SMILES just like '[CLS]C[C@@H](O)[C@H](NS(=O)(=O)c1cccs1)C(=O)NCc1ccc(C#N)cc1F' it result is tensor([[2, 1, 3]]),it is not a minority of cases，Is it possible that the vocab file is unable to encode such SMILES, or is there an issue with my environment? Your prompt response is greatly anticipated as this is very important to me

**Comment by jinhojsk515** [comment]
> 
> thanks for your patient reply，but i still have same question,for example i can encoder the SMILES '[CLS]CC(C)=CCCC(C)=CC=O' and it result is tensor([[ 2, 2, 134, 207, 248, 207, 151, 37, 3]])，but when i encoder other SMILES just like '[CLS]C[C@@H](O)[C@H](NS(=O)(=O)c1cccs1)C(=O)NCc1ccc(C#N)cc1F' it result is tensor([[2, 1, 3]]),it is not a minority of cases，Is it possible that the vocab file is unable to encode such SMILES, or is there an issue with my environment? Your prompt response is greatly anticipated as this is very important to me

SPMM doesn't utilize stereochemistry, so stereochemistry signs{'/', '\\', '@', '@@'} should be removed from the input. { e.g. smiles=Chem.MolToSmiles(Chem.MolFromSmiles(smiles), isomericSmiles=False) } The vocabulary used for the tokenizer doesn't contain these characters {see vocab_bpe_300.txt}.

Apart from that, it looks like your query SMILES C[C@@H](O)[C@H](NS(=O)(=O)c1cccs1)C(=O)NCc1ccc(C#N)cc1F cannot be read as a valid SMILES by RDKit library...

**Comment by chenlong164** [comment]
> > thanks for your patient reply，but i still have same question,for example i can encoder the SMILES '[CLS]CC(C)=CCCC(C)=CC=O' and it result is tensor([[ 2, 2, 134, 207, 248, 207, 151, 37, 3]])，but when i encoder other SMILES just like '[CLS]C[C@@H](O)[C@H](NS(=O)(=O)c1cccs1)C(=O)NCc1ccc(C#N)cc1F' it result is tensor([[2, 1, 3]]),it is not a minority of cases，Is it possible that the vocab file is unable to encode such SMILES, or is there an issue with my environment? Your prompt response is greatly anticipated as this is very important to me
> 
> SPMM doesn't handle stereochemistry, so stereochemistry signs{'/', '', '@', '@@'} should be removed from the input. { e.g. smiles=Chem.MolToSmiles(Chem.MolFromSmiles(smiles), isomericSmiles=False) } The vocabulary used for the tokenizer doesn't contain these characters {see vocab_bpe_300.txt}.
> 
> Apart from that, it looks like your query SMILES C[C@@H](O)[C@H](NS(=O)(=O)c1cccs1)C(=O)NCc1ccc(C#N)cc1F cannot be read as a valid SMILES by RDKit library...

Thank you for your patient answers, which have resolved my questions
