### ISSUE TITLE
ModuleNotFoundError: No module named 'd_pv2smiles_stochastic'

### ISSUE THREAD

**Issue by sherlockma11** [jinhojsk515/spmm#3]
ModuleNotFoundError: No module named 'd_pv2smiles_stochastic'

Hello , are you forgot some file?

**Comment by jinhojsk515** [comment]
That file was renamed to "d_pv2smiles_single.py" and it looks like we somehow forgot to change that line. Thank you for pointing it out, the module name is now fixed.
